# Generated by Django 4.0.4 on 2022-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='countryCode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
